/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_alextape_androidcamera_camera_tasks_AsyncCameraTask */

#ifndef _Included_de_alextape_androidcamera_camera_tasks_AsyncCameraTask
#define _Included_de_alextape_androidcamera_camera_tasks_AsyncCameraTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
