/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_alextape_openmaka_NativeController */

#ifndef _Included_de_alextape_openmaka_NativeController
#define _Included_de_alextape_openmaka_NativeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_initialize
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1initialize
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_test
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1test
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_displayFunction
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1displayFunction
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_glRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1glRender
  (JNIEnv *, jclass);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_glResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1glResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_configure
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1configure
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setModeObjectDetection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setModeObjectDetection
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setModeTracking
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setModeTracking
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setModeOpenGL
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setModeOpenGL
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
