/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_alextape_openmaka_NativeController */

#ifndef _Included_de_alextape_openmaka_NativeController
#define _Included_de_alextape_openmaka_NativeController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1start
  (JNIEnv *, jclass);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_initialize
 * Signature: (II[B[ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1initialize
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray, jstring);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_displayFunction
 * Signature: (II[B[I)I
 */
JNIEXPORT jint JNICALL Java_de_alextape_openmaka_NativeController_native_1displayFunction
  (JNIEnv *, jclass, jint, jint, jbyteArray, jintArray);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_glRender
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1glRender
  (JNIEnv *, jclass);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_glResize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1glResize
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_touchEvent
 * Signature: (FFI)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1touchEvent
  (JNIEnv *, jclass, jfloat, jfloat, jint);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_keyEvent
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1keyEvent
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setObjectDetection
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setObjectDetection
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setTracking
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setTracking
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     de_alextape_openmaka_NativeController
 * Method:    native_setOpenGL
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_de_alextape_openmaka_NativeController_native_1setOpenGL
  (JNIEnv *, jclass, jboolean);

#ifdef __cplusplus
}
#endif
#endif
